---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dicom-rs
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: PathPrefix(`/dicom-web`)
      kind: Rule
      services:
      - kind: Service
        name: dicom-db-orthanc
        namespace: {{ $.Release.Namespace }}
        passHostHeader: true
        port: 8042
        scheme: http
        strategy: RoundRobin
  tls:
    secretName: {{ .Values.https.certCommonName | quote }} 
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: dicom-ingressroute
  namespace: {{ $.Release.Namespace | quote }}
spec:
  entryPoints:
    - dicomtls
  routes:
    - match: HostSNI(`{{ .Values.dcmtls.certCommonName }}`)
      services:
        - name: orthweb-orthanc
          port: dicom 
  tls:
    secretName: {{ .Values.dcmtls.certCommonName | quote }} 
    passthrough: false
