apiVersion: v1
kind: Service
metadata:
  name: {{ include "orthanc.fullname" . }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "orthanc.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.httpPort }} 
      protocol: TCP
    - name: dicom
      port: {{ .Values.service.dicomPort }}
      targetPort: {{ .Values.service.dicomPort }} 
      protocol: TCP
  type: ClusterIP
  selector:
    {{- include "orthanc.selectorLabels" . | nindent 4 }}
