---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-forward-auth
data:
  INSECURE_COOKIE: 'false'
  COOKIE_DOMAIN: karofa.io
#  DOMAINS: karofa.io
  AUTH_HOST: auth.karofa.io
  URL_PATH: /_oauth
  DEFAULT_PROVIDER: oidc
  PROVIDERS_OIDC_ISSUER_URL: https://md-keycloak.md-security/realms/example
  PROVIDERS_OIDC_CLIENT_ID: traefik-forward-auth

  