# https://kubernetes.io/docs/concepts/configuration/secret/
---
apiVersion: v1
kind: Secret
metadata:
  name: traefik-forward-auth
type: Opaque
data:
  PROVIDERS_OIDC_CLIENT_SECRET: ZUl5QTFDQlcwMW5UZDhhZ2UyM3p5dWhqUzU3U28zdk4=
  SECRET: OTk3YjQwYzgyZjRhMmFkOWJhYTYzZmE1YjljMzBmYzkK
  