---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: orthanc
  namespace: {{ .Values.orthanc.namespace }}
spec:
  hosts:
  - "orthanc.karofa"
  - "orthanc"
  gateways:
  - {{ .Values.default.namespace }}/medi-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 8042
        host: {{ .Values.orthanc.release }}-orthanc
    corsPolicy:
      allowMethods:
        - POST
        - GET
        - HEAD
        - OPTIONS
        - PUT
        - DELETE
        - PATCH
      allowOrigins:
        - regex: '.*'
        - prefix: http://ohifviewer
        - prefix: https://ohifviewer
      allowHeaders:
        - Accept
