apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: keycloak-gateway
  namespace: {{ .Values.keycloak.namespace }}
spec:
  selector:
    app: {{ .Values.default.gateway }}
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "keycloak.karofa"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: keycloak
  namespace: {{ .Values.keycloak.namespace }}
spec:
  hosts:
  - "keycloak.karofa"
  - "keycloak"
  gateways:
  - keycloak-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: {{ .Values.keycloak.release }}
