---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: keycloak
  namespace: {{ .Values.keycloak.namespace }}
spec:
  hosts:
  - "keycloak.karofa"
  - "keycloak"
  gateways:
  - {{ .Values.default.namespace }}/medi-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: {{ .Values.keycloak.release }}
    # Changes needed when upgrading from to keycloak 17+
    # headers:
    #   request:
    #     set:
    #       x-forwarded-host: "keycloak.karofa"
    #       x-forwarded-port: "443"
    #       x-forwarded-proto: https
