apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: logging-gateway
  namespace: {{ .Values.logging.namespace }}
spec:
  selector:
    app: {{ .Values.default.gateway }}
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "logging.karofa"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: logging
  namespace: {{ .Values.logging.namespace }}
spec:
  hosts:
  - "logging.karofa"
  - "logging"
  gateways:
  - logging-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: {{ .Values.logging.release }}-grafana
