apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: logging
  namespace: {{ .Values.logging.namespace }}
spec:
  hosts:
  - "logging.karofa"
  - "logging"
  gateways:
  - {{ .Values.default.namespace }}/medi-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: {{ .Values.logging.release }}-grafana
