apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: medi-gateway
  namespace: {{ .Values.default.namespace }}
spec:
  selector:
    app: {{ .Values.default.gateway }}
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - '*'
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: medi-tls-credential # must be the same as secret
    hosts:
    - '*'

