apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: monitoring-gateway
  namespace: {{ .Values.monitoring.namespace }}
spec:
  selector:
    app: {{ .Values.default.gateway }}
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "monitoring.karofa"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: monitoring
  namespace: {{ .Values.monitoring.namespace }}
spec:
  hosts:
  - "monitoring.karofa"
  - "monitoring"
  gateways:
  - monitoring-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: {{ .Values.monitoring.release }}-grafana
