---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ohifviewer
  namespace: {{ .Values.ohifviewer.namespace }}
spec:
  hosts:
  - "ohifviewer.karofa"
  - "ohifviewer"
  gateways:
  - {{ .Values.default.namespace }}/medi-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: {{ .Values.ohifviewer.release }}
    corsPolicy:
      allowOrigins:
        - regex: '.*'
        - prefix: http://ohifviewer
      allowMethods:
        - POST
        - GET
        - HEAD
        - OPTIONS
        - PUT
        - DELETE
        - PATCH
      allowHeaders:
        - Accept
        - Authorization
        - Content-Type
