---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ohifviewer
  namespace: {{ .Values.ohifviewer.namespace }}
spec:
  hosts:
  - "ohifviewer.karofa"
  - "ohifviewer"
  gateways:
  - {{ .Values.default.namespace }}/medi-gateway
  http:
  - match:
      - uri:
          prefix: /auth
    route:
      - destination:
          host: md-keycloak.md-security.svc.cluster.local
          port:
            number: 80
  - match:
      - uri:
          prefix: /oauth2
    route:
      - destination:
          host: ohifviewer-oauth2-proxy.cedimat.svc.cluster.local
          port:
            number: 80
  - route:
    - destination:
        port:
          number: 80
        host: {{ .Values.ohifviewer.release }}
    corsPolicy:
      allowOrigins:
        - regex: '.*'
        - prefix: http://ohifviewer
        - prefix: https://ohifviewer
      allowMethods:
        - POST
        - GET
        - HEAD
        - OPTIONS
        - PUT
        - DELETE
        - PATCH
      allowHeaders:
        - Accept
        - Authorization
        - Content-Type
---
kind: AuthorizationPolicy
apiVersion: security.istio.io/v1beta1
metadata:
  name: ohifviewer-oauth2-proxy
  namespace: {{ .Values.ohifviewer.namespace }}
spec:
  selector:
    matchLabels:
       app: ohif-viewer
  action: CUSTOM
  provider:
    name: ohifviewer-proxy
  rules:
    - to:
        - operation:
            hosts: ["ohifviewer.karofa", "ohifviewer.karofa:*"]
            notPaths: ["/auth/*"]
