---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
spec:
  hosts:
  - "{{ .Release.Name }}.karofa"
  - "{{ .Release.Name }}"
  gateways:
  - {{ .Values.gateway.namespace }}/{{ .Values.gateway.name }}
  http:
  - match:
      - uri:
          prefix: /auth
    route:
      - destination:
          host: md-keycloak.md-security.svc.cluster.local
          port:
            number: 80
  - match:
      - uri:
          prefix: /oauth2
    route:
      - destination:
          host: oauth2-proxy.cedimat.svc.cluster.local
          port:
            number: 80
  - route:
      - destination:
          host: httpbin
          port:
            number: 8000

