# apiVersion: networking.istio.io/v1alpha3
# kind: Gateway
# metadata:
#   name: {{ .Values.setup_data_keycloak.keycloak.release }}-gateway
# spec:
#   selector:
#     app: istio-ingress
#   servers:
#   - port:
#       number: 80
#       name: http
#       protocol: HTTP
#     hosts:
#     - "keycloak.karofa"
# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   name: {{ .Values.setup_data_keycloak.keycloak.release }}
# spec:
#   hosts:
#   - "keycloak.karofa"
#   - "keycloak"
#   gateways:
#   - {{ .Values.setup_data_keycloak.keycloak.release }}-gateway
#   http:
#   - match:
#     - uri:
#         prefix: /
#     route:
#     - destination:
#         port:
#           number: 80
#         host: {{ .Values.setup_data_keycloak.keycloak.release }}
