apiVersion: v1
kind: Secret
metadata:
  name: oauth-secrets
type: Opaque
data:
  {{- range .Values.oauth_clients }}
  {{ .client_id | snakecase | upper }}_SECRET: {{ .client_secret | b64enc }}
  {{- end }}


