kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: dicom-local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dicom-data
spec:
  capacity:
    storage: {{ .Values.dicomdata.node.size }}
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: dicom-local-storage
  local:
    path: {{ .Values.dicomdata.node.localpath }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ .Values.dicomdata.node.affinity }}
