kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dicom-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: dicom-local-storage
  resources:
    requests:
      storage: {{ .Values.dicomdata.node.size }}
