metrics:
  ## @param metrics.enabled Start metrics
  ##
  enabled: true
  ## @param metrics.serviceMonitor.enabled Create ServiceMonitor resource(s) for scraping metrics using PrometheusOperator
  ## @param metrics.serviceMonitor.additionalLabels Additional labels that can be used so ServiceMonitor resource(s) can be discovered by Prometheus
  serviceMonitor:
    enabled: true
    additionalLabels:
      mdmonitor: enabled
  ## @param installCRDs Flag to install Cert Manager CRDs
##
installCRDs: true
## @param replicaCount Number of Cert Manager replicas
##
replicaCount: 1
# This startupapicheck is a Helm post-install hook that waits for the webhook
# endpoints to become available.
# The check is implemented using a Kubernetes Job- if you are injecting mesh
# sidecar proxies into cert-manager pods, you probably want to ensure that they
# are not injected into this Job's pod. Otherwise the installation may time out
# due to the Job never being completed because the sidecar proxy does not exit.
# See https://github.com/cert-manager/cert-manager/pull/4414 for context.
startupapicheck:
  enabled: true

  # Optional additional annotations to add to the startupapicheck Pods
  podLabels:
    sidecar.istio.io/inject: "false"

