metrics:
  ## @param metrics.enabled Start metrics
  ##
  enabled: true
  ## @param metrics.serviceMonitor.enabled Create ServiceMonitor resource(s) for scraping metrics using PrometheusOperator
  ## @param metrics.serviceMonitor.additionalLabels Additional labels that can be used so ServiceMonitor resource(s) can be discovered by Prometheus
  serviceMonitor:
    enabled: true
    additionalLabels:
      mdmonitor: enabled