apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opa-certs-tls
spec:
  # Secret names are always required.
  secretName: opa-tls-cert
  isCA: true
  privateKey:
    algorithm: {{ .Values.encryption.algorithm }}
    size: {{ .Values.encryption.size }}
    encoding: {{ .Values.encryption.encoding }}
  # secretTemplate is optional. If set, these annotations and labels will be
  # copied to the Secret named example-com-tls. These labels and annotations will
  # be re-reconciled if the Certificate's secretTemplate changes. secretTemplate
  # is also enforced, so relevant label and annotation changes on the Secret by a
  # third party will be overwriten by cert-manager to match the secretTemplate.
  secretTemplate:
    annotations:
      medi-deployment: "medi-paas"
    labels:
      my-secret-label: foo
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: opa-envoy
  subject:
    organizations:
      - opa-envoy
  usages:
    - digital signature
    - key encipherment
    - data encipherment
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
    - admission-controller.opa-istio.svc
  ipAddresses:
    - 192.168.2.244
  # Issuer references are always required.
  issuerRef:
    name: ca-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io  
---
