---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cm
data:
  app-config.js: |
    window.config = {
      routerBasename: '/',
      servers: {
        dicomWeb: [
          {
            name: 'Orthanc',
            wadoUriRoot: 'http://192.168.2.242:30875/wado',
            qidoRoot: 'http://192.168.2.242:30875/dicom-web',
            wadoRoot: 'http://192.168.2.242:30875/dicom-web',
            qidoSupportsIncludeField: false,
            imageRendering: 'wadors',
            thumbnailRendering: 'wadors',
        ],
      },
    };

